# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
#orbs:
#  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
## Orchestrate or schedule a set of jobs

jobs:
  delete_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: ./scripts/delete_cf.sh test
      - run:
          command: sleep 150
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: ./scripts/create_cf.sh test template.yml
  describe_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: ./scripts/describe.sh
#      - persist_to_workspace:
#          root:  ~/
#          paths:
#            - inventory.txt
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
#      - run:
#          command: sudo apt-get install -y tar
#      - attach_workspace:
#          at: ~/
      - add_ssh_keys:
          fingerprints:
            - "7d:ae:fe:8b:fd:e5:57:57:c4:8c:51:1e:e1:c3:d5:59"
      - run:
          name: Install dependencies
          command: apk add --update ansible
      - run:
          name: Configure server
          command: ansible-playbook -i inventory.txt playbook.yml

workflows:
  # Name the workflow "welcome"
  testing:
    # Run the welcome/run job in its own container
    jobs:
      - delete_infrastructure
      - create_infrastructure:
          requires:
            - delete_infrastructure
      - describe_infrastructure:
          requires:
            - create_infrastructure
      - configure_infrastructure:
          requires:
            - describe_infrastructure
