# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
#orbs:
#  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
## Orchestrate or schedule a set of jobs
commands:
  delete_infrastructure:
    steps:
      - run:
          command: ./scripts/delete_cf.sh
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: ./scripts/create_cf.sh test-${CIRCLE_WORKFLOW_ID} template.yml
      - run:
          command: return 1
      - delete_infrastructure
        when: on_fail


workflows:
  testing:
    jobs:
      - create_infrastructure